/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  application_business: () => import("@/views/application/business/index.vue"),
  application_exchange: () => import("@/views/application/exchange/index.vue"),
  application_leave: () => import("@/views/application/leave/index.vue"),
  application_makeup: () => import("@/views/application/makeup/index.vue"),
  application_overtime: () => import("@/views/application/overtime/index.vue"),
  application_regularization: () => import("@/views/application/regularization/index.vue"),
  application_resignation: () => import("@/views/application/resignation/index.vue"),
  application_reward: () => import("@/views/application/reward/index.vue"),
  application_transfer: () => import("@/views/application/transfer/index.vue"),
  approval_flow: () => import("@/views/approval/flow/index.vue"),
  approval_mine: () => import("@/views/approval/mine/index.vue"),
  approval_pending: () => import("@/views/approval/pending/index.vue"),
  attendance_clock: () => import("@/views/attendance/clock/index.vue"),
  attendance_daily: () => import("@/views/attendance/daily/index.vue"),
  attendance_holiday: () => import("@/views/attendance/holiday/index.vue"),
  attendance_monthly: () => import("@/views/attendance/monthly/index.vue"),
  attendance_schedule: () => import("@/views/attendance/schedule/index.vue"),
  attendance_shift: () => import("@/views/attendance/shift/index.vue"),
  home: () => import("@/views/home/index.vue"),
  hr_contract: () => import("@/views/hr/contract/index.vue"),
  hr_employee: () => import("@/views/hr/employee/index.vue"),
  "organization_org-structure": () => import("@/views/organization/org-structure/index.vue"),
  report_attendance: () => import("@/views/report/attendance/index.vue"),
  report_employee: () => import("@/views/report/employee/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
