/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'application',
    path: '/application',
    component: 'layout.base',
    meta: {
      title: 'application',
      i18nKey: 'route.application',
      order: 5,
      icon: 'mdi:file-document-multiple'
    },
    children: [
      {
        name: 'application_business',
        path: '/application/business',
        component: 'view.application_business',
        meta: {
          title: 'application_business',
          i18nKey: 'route.application_business',
          order: 5,
          icon: 'mdi:airplane'
        }
      },
      {
        name: 'application_exchange',
        path: '/application/exchange',
        component: 'view.application_exchange',
        meta: {
          title: 'application_exchange',
          i18nKey: 'route.application_exchange',
          order: 5,
          icon: 'mdi:swap-horizontal-circle'
        }
      },
      {
        name: 'application_leave',
        path: '/application/leave',
        component: 'view.application_leave',
        meta: {
          title: 'application_leave',
          i18nKey: 'route.application_leave',
          order: 5,
          icon: 'mdi:beach'
        }
      },
      {
        name: 'application_makeup',
        path: '/application/makeup',
        component: 'view.application_makeup',
        meta: {
          title: 'application_makeup',
          i18nKey: 'route.application_makeup',
          order: 5,
          icon: 'mdi:clock-check'
        }
      },
      {
        name: 'application_overtime',
        path: '/application/overtime',
        component: 'view.application_overtime',
        meta: {
          title: 'application_overtime',
          i18nKey: 'route.application_overtime',
          order: 5,
          icon: 'mdi:clock-plus'
        }
      },
      {
        name: 'application_regularization',
        path: '/application/regularization',
        component: 'view.application_regularization',
        meta: {
          title: 'application_regularization',
          i18nKey: 'route.application_regularization',
          order: 5
        }
      },
      {
        name: 'application_resignation',
        path: '/application/resignation',
        component: 'view.application_resignation',
        meta: {
          title: 'application_resignation',
          i18nKey: 'route.application_resignation',
          order: 5
        }
      },
      {
        name: 'application_reward',
        path: '/application/reward',
        component: 'view.application_reward',
        meta: {
          title: 'application_reward',
          i18nKey: 'route.application_reward',
          order: 5
        }
      },
      {
        name: 'application_transfer',
        path: '/application/transfer',
        component: 'view.application_transfer',
        meta: {
          title: 'application_transfer',
          i18nKey: 'route.application_transfer',
          order: 5
        }
      }
    ]
  },
  {
    name: 'approval',
    path: '/approval',
    component: 'layout.base',
    meta: {
      title: 'approval',
      i18nKey: 'route.approval',
      order: 6,
      icon: 'mdi:check-decagram'
    },
    children: [
      {
        name: 'approval_flow',
        path: '/approval/flow',
        component: 'view.approval_flow',
        meta: {
          title: 'approval_flow',
          i18nKey: 'route.approval_flow',
          order: 6,
          icon: 'mdi:sitemap'
        }
      },
      {
        name: 'approval_mine',
        path: '/approval/mine',
        component: 'view.approval_mine',
        meta: {
          title: 'approval_mine',
          i18nKey: 'route.approval_mine',
          order: 6,
          icon: 'mdi:file-document-check'
        }
      },
      {
        name: 'approval_mobile-approver',
        path: '/approval/mobile-approver',
        component: 'view.approval_mobile-approver',
        meta: {
          title: 'approval_mobile-approver',
          i18nKey: 'route.approval_mobile-approver',
          order: 6
        }
      },
      {
        name: 'approval_pending',
        path: '/approval/pending',
        component: 'view.approval_pending',
        meta: {
          title: 'approval_pending',
          i18nKey: 'route.approval_pending',
          order: 6,
          icon: 'mdi:clock-alert'
        }
      }
    ]
  },
  {
    name: 'attendance',
    path: '/attendance',
    component: 'layout.base',
    meta: {
      title: 'attendance',
      i18nKey: 'route.attendance',
      order: 4,
      icon: 'mdi:clock-outline'
    },
    children: [
      {
        name: 'attendance_clock',
        path: '/attendance/clock',
        component: 'view.attendance_clock',
        meta: {
          title: 'attendance_clock',
          i18nKey: 'route.attendance_clock',
          order: 4
        }
      },
      {
        name: 'attendance_daily',
        path: '/attendance/daily',
        component: 'view.attendance_daily',
        meta: {
          title: 'attendance_daily',
          i18nKey: 'route.attendance_daily',
          order: 4,
          icon: 'mdi:calendar-today'
        }
      },
      {
        name: 'attendance_holiday',
        path: '/attendance/holiday',
        component: 'view.attendance_holiday',
        meta: {
          title: 'attendance_holiday',
          i18nKey: 'route.attendance_holiday',
          order: 4,
          icon: 'mdi:calendar-star'
        }
      },
      {
        name: 'attendance_location',
        path: '/attendance/location',
        component: 'view.attendance_location',
        meta: {
          title: 'attendance_location',
          i18nKey: 'route.attendance_location',
          order: 3,
          icon: 'mdi:map-marker-radius'
        }
      },
      {
        name: 'attendance_monthly',
        path: '/attendance/monthly',
        component: 'view.attendance_monthly',
        meta: {
          title: 'attendance_monthly',
          i18nKey: 'route.attendance_monthly',
          order: 4,
          icon: 'mdi:calendar-month'
        }
      },
      {
        name: 'attendance_schedule',
        path: '/attendance/schedule',
        component: 'view.attendance_schedule',
        meta: {
          title: 'attendance_schedule',
          i18nKey: 'route.attendance_schedule',
          order: 4,
          icon: 'mdi:calendar-clock'
        }
      },
      {
        name: 'attendance_shift',
        path: '/attendance/shift',
        component: 'view.attendance_shift',
        meta: {
          title: 'attendance_shift',
          i18nKey: 'route.attendance_shift',
          order: 4,
          icon: 'mdi:clock-time-four'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'hr',
    path: '/hr',
    component: 'layout.base',
    meta: {
      title: 'hr',
      i18nKey: 'route.hr',
      order: 3,
      icon: 'mdi:account-group'
    },
    children: [
      {
        name: 'hr_contract',
        path: '/hr/contract',
        component: 'view.hr_contract',
        meta: {
          title: 'hr_contract',
          i18nKey: 'route.hr_contract',
          order: 3,
          icon: 'mdi:file-document-edit'
        }
      },
      {
        name: 'hr_employee',
        path: '/hr/employee',
        component: 'view.hr_employee',
        meta: {
          title: 'hr_employee',
          i18nKey: 'route.hr_employee',
          order: 3,
          icon: 'mdi:account-multiple'
        }
      }
    ]
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'organization',
    path: '/organization',
    component: 'layout.base',
    meta: {
      title: 'organization',
      i18nKey: 'route.organization',
      order: 2,
      icon: 'mdi:office-building'
    },
    children: [
      {
        name: 'organization_org-structure',
        path: '/organization/org-structure',
        component: 'view.organization_org-structure',
        meta: {
          title: 'organization_org-structure',
          i18nKey: 'route.organization_org-structure',
          order: 2
        }
      }
    ]
  },
  {
    name: 'report',
    path: '/report',
    component: 'layout.base',
    meta: {
      title: 'report',
      i18nKey: 'route.report',
      order: 7,
      icon: 'mdi:chart-bar'
    },
    children: [
      {
        name: 'report_attendance',
        path: '/report/attendance',
        component: 'view.report_attendance',
        meta: {
          title: 'report_attendance',
          i18nKey: 'route.report_attendance',
          order: 7,
          icon: 'mdi:chart-line'
        }
      },
      {
        name: 'report_employee',
        path: '/report/employee',
        component: 'view.report_employee',
        meta: {
          title: 'report_employee',
          i18nKey: 'route.report_employee',
          order: 7,
          icon: 'mdi:chart-pie'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      order: 8,
      icon: 'mdi:cog'
    },
    children: [
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict',
          order: 8,
          icon: 'mdi:book-alphabet'
        }
      },
      {
        name: 'system_feedback',
        path: '/system/feedback',
        component: 'view.system_feedback',
        meta: {
          title: 'system_feedback',
          i18nKey: 'route.system_feedback',
          order: 8,
          icon: 'mdi:message-alert-outline'
        }
      },
      {
        name: 'system_file-config',
        path: '/system/file-config',
        component: 'view.system_file-config',
        meta: {
          title: 'system_file-config',
          i18nKey: 'route.system_file-config',
          order: 8
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          order: 8,
          icon: 'mdi:menu'
        }
      },
      {
        name: 'system_mobile-menu',
        path: '/system/mobile-menu',
        component: 'view.system_mobile-menu',
        meta: {
          title: 'system_mobile-menu',
          i18nKey: 'route.system_mobile-menu',
          order: 8
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice',
          order: 8
        }
      },
      {
        name: 'system_oper-log',
        path: '/system/oper-log',
        component: 'view.system_oper-log',
        meta: {
          title: 'system_oper-log',
          i18nKey: 'route.system_oper-log',
          order: 8
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          order: 8
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          order: 8
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: '个人中心',
      titleEn: 'User Center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
